### PR TITLE
Implement PDF open menu item for Desktop and Android

### LINKED ISSUE #9: Feature Request - Ability to open embedded PDFs in the default app
It will help to share them especially on the mobile app. Similar to the sharing images one

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes #9

### CODE REVIEW

**Comment by NomarCub** [comment]
Is it normal that the menu only appears on about every third hover?  
Also, did the normal right-click menu not work? This hover behaviour doesn't mesh well with the others for me.

**Comment by mnaoumov** [comment]
Every third hover is definitely not right. I worked for me fine, but I'll take another look.

Right click menu doesn't work as this JavaScript event doesn't bubble up in the existing markup

**Comment by mnaoumov** [comment]
@NomarCub slightly improved the UX

**Comment by NomarCub** [comment]
Hovers are consistent now, thanks!
I will merge and publish shortly. Depending on future feedback I might make this optional (and disabled by default, as it's kind of different from the other features).

**Pull request merged**
